Lab1.cpp
MAX_LOADSTRING
Referenced by wWinMain.
HINSTANCE hInst
Referenced by InitInstance, WndProc, Work1.
WCHAR szTitle[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by InitInstance, wWinMain.
WCHAR szWindowClass[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by InitInstance, MyRegisterClass, wWinMain.
int fontHeight
char fontName[][]
int textHeightPosition
Referenced by WndProc.
int textWidthPosition
Referenced by WndProc.
HFONT hFont
Referenced by WndProc.
ATOM MyRegisterClass(HINSTANCE hInstance)
References IDC_LAB1, IDI_LAB1, IDI_SMALL, szWindowClass, WndProc.
Referenced by wWinMain.
BOOL InitInstance(HINSTANCE, int)
References hInst, szTitle, szWindowClass.
Referenced by wWinMain.
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM)
References About, canWrite, hFont, hInst, IDD_ABOUTBOX, IDM_ABOUT, IDM_EXIT, IDM_WORK_MOD1, IDM_WORK_MOD2, maxSymbols, pos, tempPlaceForText, textHeightPosition, textWidthPosition, Work1.
Referenced by MyRegisterClass.
INT_PTR CALLBACK About(HWND, UINT, WPARAM, LPARAM)
Referenced by WndProc.
void Work1(HWND hWnd)
References hInst, IDD_WORK_MOD1, Work1_MOD1.
Referenced by WndProc.
int APIENTRY wWinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPWSTR lpCmdLine, _In_ int nCmdShow)
References IDC_LAB1, IDS_APP_TITLE, InitInstance, MAX_LOADSTRING, MyRegisterClass, szTitle, szWindowClass.